# Generated by Django 4.1.7 on 2023-05-31 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_myproject_piece_joinde'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Data_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
