# Generated by Django 4.1.7 on 2023-05-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_data_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Data_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
