# Generated by Django 4.1.7 on 2023-06-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_alter_client_image_alter_supervisor_image'),
        ('map', '0040_alter_data_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='clientp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='signup.client'),
        ),
    ]
